### ISSUE TITLE
难以忍受这句话。。想想还是觉得要发一下。。=。=

### ISSUE THREAD

**Issue by wzyy2** [phodal/designiot#1]
‘如果你还想用C学理论的话，烦请出门左拐。我想，C并不适合于学习相关硬件的理论’

真的。。任何一个mcu或者linux driver开发者都不会忍受这句话。。

我没写过arduino，我不知道arduino能学硬件的理论，spi，i2c？就是硬件理论了？
mcu上的软件开发所面临的东西远比这要复杂的多。

**Comment by phodal** [comment]
我的意思是，用Arduino比较快。。:-)
@_@觉得不合适就改一下，欢迎参与。

**Comment by yangquan3** [comment]
过程不重要，结果才是你想要的
