### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by reatang** [phodal/designiot#13]
之前在树莓派3出来的时候乘着劲儿就买了一个，至今除了通电装了个lnmp环境就没用过了，拜读文章感觉对IOT又多了一些了解。
非常有幸的是文章中除了coap协议比较生疏，其他的技术都会。果然是学了技术一定得用在什么地方才能展现它的力量。准备再买几个硬件玩玩Geek啦~

**Comment by phodal** [comment]
@reatang 可以支持下纸质版，哈哈~

**Comment by reatang** [comment]
支持md程序员/滑稽
