### ISSUE TITLE
建议使用Markdown重新排版并且发布到GitBook上

### ISSUE THREAD

**Issue by zhengruiw02** [phodal/designiot#4]
既然使用了CC-NC-4.0发布了，建议使用Markdown重新排版并且发布到GitBook上，方便转换为mobi或者epub格式，放在kindle等设备上阅读！

**Comment by phodal** [comment]
@zhengruiw02 

今天才看到这个，提议挺好的~~，现在比较关心内容怎样。

**Comment by zhengruiw02** [comment]
对于一个EE毕业，刚入行Embedded的程序猿来说，一些内容还是比较新颖的，终于可以有东西跟那群web前端后端的朋友同学说上两句了。蜻蜓点水式的内容，对初学者还是不错。我都是一个月前看了大半本书，估计有所遗忘了，倒是开篇说要抛弃C语言让人无语，应该是说C都不懂还跑过来干嘛。。不过章节之间连贯性不多，有点感觉是为了介绍而介绍。

**Comment by phodal** [comment]
@zhengruiw02 

好提议: `C都不懂还跑过来干嘛`。毕竟，很多东西都是从毕业论文中拿过来的~~。
