### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by xixiaofinland** [phodal/designiot#8]
文章的题目叫_一步步搭建物联网系统(教你设计物联网系统)_, 却花了很大的篇幅介绍1-17章的东西。 不是说那些知识没用，只是感觉有点头重脚轻。

从18章开始是真正的IoT, 段落标题逻辑都很清晰,介绍了硬件通信，硬件(arduino)， 各种语言写IoT代码， 还有Android示例。但是里面的内容就有点散乱，上下逻辑不太严谨。 比如：突然出现了温度和湿度传感器接收到的数据, 我就迷惑是arduino有这两种传感器还是什么， 这个并没有介绍。

从读者的角度， 我可能更喜欢看到一步步搭建成功的例子，如果我手上有相同的硬件我可以跟上完成每一步最后实现这个简答IoT。

**Comment by phodal** [comment]
嗯~~，谢谢哈。

不过，已经不维护了。。
